export const actionTypes = {
    SHOW_LOADER: 'SHOW_LOADER',
    HIDE_LOADER: 'HIDE_LOADER',
    SHOW_ALERT: 'SHOW_ALERT',
    HIDE_ALERT: 'HIDE_ALERT',
    CHANGE_THEME: 'CHANGE_THEME',
    SET_GEOLOCATION: 'SET_GEOLOCATION',
    SET_CURRENT_CITY: 'SET_CURRENT_CITY',
    SET_CURRENT_WEATHER: 'SET_CURRENT_WEATHER',
    SET_DAILY_FORECAST: 'SET_DAILY_FORECAST',
    ADD_TO_FAVORITE: 'ADD_TO_FAVORITE',
    REMOVE_FROM_FAVORITE: 'REMOVE_FROM_FAVORITE',
    GET_DATA_FROM_LOCALSTORAGE: 'GET_DATA_FROM_LOCALSTORAGE',
    CHANGE_TEMPERATURE_TYPE: 'CHANGE_TEMPERATURE_TYPE'
}
